name: Build and Release

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  releases-windows-amd64:
    name: Release windows-amd64
    runs-on: ubuntu-latest  # Change to your desired runner environment
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: windows
          goarch: amd64
          executable_compression: upx --best
          asset_name: NorlandDemoUnlocker
          sha256sum: true
          compress_assets: false
            
            
#     - name: Get executable path
#       run: echo NorlandDemoUnlocker.exe
#     - name: Calculate SHA-256 sum
#       run: shasum -a 256 ${{ steps.get_executable_path.outputs.path }}
#     - name: Add SHA-256 sum to release notes
#       run: | 
#       echo "SHA-256 sum: {{ steps.calculate_sha256_sum.outputs.stdout }}" >> ${{ github.workspace }}/release-notes.md
